In [1]:
list1 = [1,2,3]
import numpy as np


In [7]:
arr= np.array(list1)

In [9]:
arr


array([1, 2, 3])

In [10]:
my_math = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_math

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(0)

array([], dtype=float64)

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [26]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.65585155, 0.75324344, 0.99532919, 0.40906699, 0.04481015])

In [31]:
np.random.rand(2,3)

array([[0.19211505, 0.59162164, 0.25787378],
       [0.70278392, 0.88615875, 0.2469789 ]])

In [32]:
np.random.randn(4,5)

array([[-0.87403096, -0.46288428,  0.51200982, -0.94157954,  0.45117083],
       [-0.37948461,  0.52566544,  1.49475438,  0.68061949,  0.93441883],
       [-1.3420869 ,  1.57614412, -0.84618751,  0.02138448, -1.53875471],
       [-0.82688435,  0.96967104,  0.74208135,  1.28608404, -0.75625234]])

In [33]:
np.random.randint(1,100,5)

array([48, 79, 59,  6, 67])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([42,  6, 24, 13, 48,  5, 24, 36, 26, 16])

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr

array([42,  6, 24, 13, 48,  5, 24, 36, 26, 16])

In [51]:
ranarr.max()

48

In [52]:
ranarr.min()

5

In [53]:
ranarr.argmax()

4

In [54]:
ranarr.argmin()

5

In [55]:
ranarr.shape

(10,)

In [62]:
newarr = ranarr.reshape(5,2)
newarr

array([[42,  6],
       [24, 13],
       [48,  5],
       [24, 36],
       [26, 16]])

In [63]:
newarr.shape

(5, 2)

In [64]:
arr.dtype

dtype('int32')

In [65]:
from numpy.random import randint

In [68]:
randint(2,10,5)

array([5, 6, 3, 5, 8])