In [1]:
import numpy as np

In [10]:
arr =np.arange(11,22)

In [11]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [12]:
#indexing
arr[8]

19

In [13]:
arr[2:5]

array([13, 14, 15])

In [14]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [15]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [16]:
arr[:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,  16,  17,  18,  19,  20,  21])

In [20]:
#numpy indexing changes affects the original array also
arr = np.arange(0,11)

In [26]:
slice_of_arr = arr[:5]

In [27]:
slice_of_arr[:] = 111

In [28]:
slice_of_arr

array([111, 111, 111, 111, 111])

In [29]:
arr

array([111, 111, 111, 111, 111,   5,   6,   7,   8,   9,  10])

In [30]:
#to prevent this use copy method
arr_copy = arr.copy()

In [31]:
arr_copy

array([111, 111, 111, 111, 111,   5,   6,   7,   8,   9,  10])

In [32]:
arr

array([111, 111, 111, 111, 111,   5,   6,   7,   8,   9,  10])

In [33]:
arr_copy[:] = 200

In [34]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [35]:
arr

array([111, 111, 111, 111, 111,   5,   6,   7,   8,   9,  10])